Toolkit: Raise nonexisting JAR Resources at the right place.
Ie. when we don't have a file requested to be loaded by IOUtils, we print this error:

> java.lang.IllegalArgumentException: Error: Toolkit file eu/exahype/plotters/templates/UserDefinedDeviceHeader.template not found (java.lang.NullPointerException) during loading in convertRessourceContentToString. Make sure it is compiled into the toolkit

The actual file missing here will be commited by Dominic in 40 Minutes :)